### ISSUE TITLE
Start-app todo

### ISSUE THREAD

**Issue by dy** [dfcreative/prama#1]
- [x] `label` property
- [x] `help` property (value of range etc.)
- [x] `button` type - to react on event
- [x] `range` type with 2 values (actual range)
- [x] `range` type with fixed choices (fftSize for example)
- [x] nested params, like `type` enables `width` etc.
- [x] a separate module
- [x] reload required

**Comment by dy** [comment]
Nested params done via change callback - just hide/show needed as `setParam(name, {hidden: true})`

**Comment by dy** [comment]
Reload required is set through help text
