### ISSUE TITLE
Demo checklist

### ISSUE THREAD

**Issue by dy** [dfcreative/prama#11]
- [x] Add palette chooser
- [ ] Add help text to the panel
- [x] Regulate the label width from sidebar
- [ ] Default scheme is of the logo
- [ ] Logo on the demo page with link
- [ ] Add icons to orientation choose
- [x] Remove alert on enter
- [x] Add width controller
- [x] Make body adjust to (at least) height of the popup.
- [x] Make font chooser.
- [ ] Add icon choose.
- [ ] Add generate code button.
